%% <module> ctrlstrct
% Autogenerated by rdfs2pl -- see https://github.com/cmungall/rdfs2pl/

:-module(ctrlstrct,[afterTraceEnd/1,correspondingEndMismatched/1,correspondingEndPerformedDifferentTime/1,debugObj/1,duplicateActInSequence/1,erroneous/1,functionBegin/1,sequenceBegin/1,sequenceEnd/1,sequenceNext/1,stmtEnd/1,wrongExecTime/1,act/1,act_begin/1,act_end/1,algorithm/1,correct_act/1,current_act/1,first_item/1,func/1,last_item/1,sequence/1,stmt/1,student_act/1,trace/1,trace_error/1,algorithm_name/2,arg/2,body/2,body_item/2,cause/2,contains_act/2,contains_child/2,corresponding_end/2,entry_point/2,exec_time/2,executes/2,expr_value/2,functions_item/2,global_code/2,id/2,in_trace/2,index/2,message/2,next/2,next_sibling/2,parent_of/2,should_be/2,text_line/2,algorithm_name/3,arg/3,body/3,body_item/3,cause/3,contains_act/3,contains_child/3,corresponding_end/3,entry_point/3,exec_time/3,executes/3,expr_value/3,functions_item/3,global_code/3,id/3,in_trace/3,index/3,message/3,next/3,next_sibling/3,parent_of/3,should_be/3,text_line/3,op(300,xfy,algorithm_name),op(300,xfy,arg),op(300,xfy,body),op(300,xfy,body_item),op(300,xfy,cause),op(300,xfy,contains_act),op(300,xfy,contains_child),op(300,xfy,corresponding_end),op(300,xfy,entry_point),op(300,xfy,exec_time),op(300,xfy,executes),op(300,xfy,expr_value),op(300,xfy,functions_item),op(300,xfy,global_code),op(300,xfy,id),op(300,xfy,in_trace),op(300,xfy,index),op(300,xfy,message),op(300,xfy,next),op(300,xfy,next_sibling),op(300,xfy,parent_of),op(300,xfy,should_be),op(300,xfy,text_line)]).
:-use_module(library(semweb/rdf11)).
:-use_module(library(semweb/rdfs)).

:-op(300,xfy,algorithm_name).
:-op(300,xfy,arg).
:-op(300,xfy,body).
:-op(300,xfy,body_item).
:-op(300,xfy,cause).
:-op(300,xfy,contains_act).
:-op(300,xfy,contains_child).
:-op(300,xfy,corresponding_end).
:-op(300,xfy,entry_point).
:-op(300,xfy,exec_time).
:-op(300,xfy,executes).
:-op(300,xfy,expr_value).
:-op(300,xfy,functions_item).
:-op(300,xfy,global_code).
:-op(300,xfy,id).
:-op(300,xfy,in_trace).
:-op(300,xfy,index).
:-op(300,xfy,message).
:-op(300,xfy,next).
:-op(300,xfy,next_sibling).
:-op(300,xfy,parent_of).
:-op(300,xfy,should_be).
:-op(300,xfy,text_line).

:-rdf_meta ctrlstrct:act(r).

:-rdf_meta ctrlstrct:act_begin(r).

:-rdf_meta ctrlstrct:act_end(r).

:-rdf_meta ctrlstrct:afterTraceEnd(r).

:-rdf_meta ctrlstrct:algorithm(r).

:-rdf_meta ctrlstrct:correct_act(r).

:-rdf_meta ctrlstrct:correspondingEndMismatched(r).

:-rdf_meta ctrlstrct:correspondingEndPerformedDifferentTime(r).

:-rdf_meta ctrlstrct:current_act(r).

:-rdf_meta ctrlstrct:debugObj(r).

:-rdf_meta ctrlstrct:duplicateActInSequence(r).

:-rdf_meta ctrlstrct:erroneous(r).

:-rdf_meta ctrlstrct:first_item(r).

:-rdf_meta ctrlstrct:func(r).

:-rdf_meta ctrlstrct:functionBegin(r).

:-rdf_meta ctrlstrct:last_item(r).

:-rdf_meta ctrlstrct:sequence(r).

:-rdf_meta ctrlstrct:sequenceBegin(r).

:-rdf_meta ctrlstrct:sequenceEnd(r).

:-rdf_meta ctrlstrct:sequenceNext(r).

:-rdf_meta ctrlstrct:stmt(r).

:-rdf_meta ctrlstrct:stmtEnd(r).

:-rdf_meta ctrlstrct:student_act(r).

:-rdf_meta ctrlstrct:trace(r).

:-rdf_meta ctrlstrct:trace_error(r).

:-rdf_meta ctrlstrct:wrongExecTime(r).

:-rdf_meta ctrlstrct:algorithm_name(r,r).

:-rdf_meta ctrlstrct:arg(r,r).

:-rdf_meta ctrlstrct:body(r,r).

:-rdf_meta ctrlstrct:body_item(r,r).

:-rdf_meta ctrlstrct:cause(r,r).

:-rdf_meta ctrlstrct:contains_act(r,r).

:-rdf_meta ctrlstrct:contains_child(r,r).

:-rdf_meta ctrlstrct:corresponding_end(r,r).

:-rdf_meta ctrlstrct:entry_point(r,r).

:-rdf_meta ctrlstrct:exec_time(r,r).

:-rdf_meta ctrlstrct:executes(r,r).

:-rdf_meta ctrlstrct:expr_value(r,r).

:-rdf_meta ctrlstrct:functions_item(r,r).

:-rdf_meta ctrlstrct:global_code(r,r).

:-rdf_meta ctrlstrct:id(r,r).

:-rdf_meta ctrlstrct:in_trace(r,r).

:-rdf_meta ctrlstrct:index(r,r).

:-rdf_meta ctrlstrct:message(r,r).

:-rdf_meta ctrlstrct:next(r,r).

:-rdf_meta ctrlstrct:next_sibling(r,r).

:-rdf_meta ctrlstrct:parent_of(r,r).

:-rdf_meta ctrlstrct:should_be(r,r).

:-rdf_meta ctrlstrct:subclass_of_arg(r,r).

:-rdf_meta ctrlstrct:subclass_of_body(r,r).

:-rdf_meta ctrlstrct:subclass_of_body_item(r,r).

:-rdf_meta ctrlstrct:subclass_of_cause(r,r).

:-rdf_meta ctrlstrct:subclass_of_contains_act(r,r).

:-rdf_meta ctrlstrct:subclass_of_contains_child(r,r).

:-rdf_meta ctrlstrct:subclass_of_corresponding_end(r,r).

:-rdf_meta ctrlstrct:subclass_of_entry_point(r,r).

:-rdf_meta ctrlstrct:subclass_of_executes(r,r).

:-rdf_meta ctrlstrct:subclass_of_functions_item(r,r).

:-rdf_meta ctrlstrct:subclass_of_global_code(r,r).

:-rdf_meta ctrlstrct:subclass_of_in_trace(r,r).

:-rdf_meta ctrlstrct:subclass_of_next(r,r).

:-rdf_meta ctrlstrct:subclass_of_next_sibling(r,r).

:-rdf_meta ctrlstrct:subclass_of_parent_of(r,r).

:-rdf_meta ctrlstrct:subclass_of_should_be(r,r).

:-rdf_meta ctrlstrct:text_line(r,r).

:-rdf_meta ctrlstrct:algorithm_name(r,r,g).

:-rdf_meta ctrlstrct:arg(r,r,g).

:-rdf_meta ctrlstrct:body(r,r,g).

:-rdf_meta ctrlstrct:body_item(r,r,g).

:-rdf_meta ctrlstrct:cause(r,r,g).

:-rdf_meta ctrlstrct:contains_act(r,r,g).

:-rdf_meta ctrlstrct:contains_child(r,r,g).

:-rdf_meta ctrlstrct:corresponding_end(r,r,g).

:-rdf_meta ctrlstrct:entry_point(r,r,g).

:-rdf_meta ctrlstrct:exec_time(r,r,g).

:-rdf_meta ctrlstrct:executes(r,r,g).

:-rdf_meta ctrlstrct:expr_value(r,r,g).

:-rdf_meta ctrlstrct:functions_item(r,r,g).

:-rdf_meta ctrlstrct:global_code(r,r,g).

:-rdf_meta ctrlstrct:id(r,r,g).

:-rdf_meta ctrlstrct:in_trace(r,r,g).

:-rdf_meta ctrlstrct:index(r,r,g).

:-rdf_meta ctrlstrct:message(r,r,g).

:-rdf_meta ctrlstrct:next(r,r,g).

:-rdf_meta ctrlstrct:next_sibling(r,r,g).

:-rdf_meta ctrlstrct:parent_of(r,r,g).

:-rdf_meta ctrlstrct:should_be(r,r,g).

:-rdf_meta ctrlstrct:text_line(r,r,g).

%! act(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#act>
%
ctrlstrct:act(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#act').

%! act_begin(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#act_begin>
%
ctrlstrct:act_begin(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#act_begin').

%! act_end(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#act_end>
%
ctrlstrct:act_end(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#act_end').

%! afterTraceEnd(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#AfterTraceEnd>
%
ctrlstrct:afterTraceEnd(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#AfterTraceEnd').

%! algorithm(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#algorithm>
%
ctrlstrct:algorithm(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#algorithm').

%! correct_act(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#correct_act>
%
ctrlstrct:correct_act(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#correct_act').

%! correspondingEndMismatched(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#CorrespondingEndMismatched>
%
ctrlstrct:correspondingEndMismatched(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#CorrespondingEndMismatched').

%! correspondingEndPerformedDifferentTime(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#CorrespondingEndPerformedDifferentTime>
%
ctrlstrct:correspondingEndPerformedDifferentTime(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#CorrespondingEndPerformedDifferentTime').

%! current_act(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#current_act>
%
ctrlstrct:current_act(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#current_act').

%! debugObj(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#DebugObj>
%
ctrlstrct:debugObj(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#DebugObj').

%! duplicateActInSequence(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#DuplicateActInSequence>
%
ctrlstrct:duplicateActInSequence(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#DuplicateActInSequence').

%! erroneous(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#Erroneous>
%
ctrlstrct:erroneous(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#Erroneous').

%! first_item(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#first_item>
%
ctrlstrct:first_item(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#first_item').

%! func(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#func>
%
ctrlstrct:func(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#func').

%! functionBegin(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#FunctionBegin>
%
ctrlstrct:functionBegin(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#FunctionBegin').

%! last_item(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#last_item>
%
ctrlstrct:last_item(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#last_item').

%! sequence(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#sequence>
%
ctrlstrct:sequence(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#sequence').

%! sequenceBegin(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#SequenceBegin>
%
ctrlstrct:sequenceBegin(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#SequenceBegin').

%! sequenceEnd(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#SequenceEnd>
%
ctrlstrct:sequenceEnd(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#SequenceEnd').

%! sequenceNext(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#SequenceNext>
%
ctrlstrct:sequenceNext(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#SequenceNext').

%! stmt(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#stmt>
%
ctrlstrct:stmt(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#stmt').

%! stmtEnd(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#StmtEnd>
%
ctrlstrct:stmtEnd(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#StmtEnd').

%! student_act(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#student_act>
%
ctrlstrct:student_act(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#student_act').

%! trace(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#trace>
%
ctrlstrct:trace(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#trace').

%! trace_error(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#trace_error>
%
ctrlstrct:trace_error(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#trace_error').

%! wrongExecTime(I)
%
%  Any instance of <http://vstu.ru/poas/ctrl_structs_2020-05_v1#WrongExecTime>
%
ctrlstrct:wrongExecTime(I):-rdfs_individual_of(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#WrongExecTime').

%! algorithm_name(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#algorithm_name>
%
ctrlstrct:algorithm_name(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#algorithm_name',J).

%! arg(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#arg>
%
ctrlstrct:arg(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#arg',J).

%! body(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#body>
%
ctrlstrct:body(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#body',J).

%! body_item(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#body_item>
%
ctrlstrct:body_item(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#body_item',J).

%! cause(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#cause>
%
ctrlstrct:cause(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#cause',J).

%! contains_act(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#contains_act>
%
ctrlstrct:contains_act(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#contains_act',J).

%! contains_child(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#contains_child>
%
ctrlstrct:contains_child(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#contains_child',J).

%! corresponding_end(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#corresponding_end>
%
ctrlstrct:corresponding_end(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#corresponding_end',J).

%! entry_point(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#entry_point>
%
ctrlstrct:entry_point(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#entry_point',J).

%! exec_time(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#exec_time>
%
ctrlstrct:exec_time(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#exec_time',J).

%! executes(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#executes>
%
ctrlstrct:executes(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#executes',J).

%! expr_value(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#expr_value>
%
ctrlstrct:expr_value(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#expr_value',J).

%! functions_item(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#functions_item>
%
ctrlstrct:functions_item(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#functions_item',J).

%! global_code(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#global_code>
%
ctrlstrct:global_code(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#global_code',J).

%! id(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#id>
%
ctrlstrct:id(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#id',J).

%! in_trace(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#in_trace>
%
ctrlstrct:in_trace(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#in_trace',J).

%! index(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#index>
%
ctrlstrct:index(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#index',J).

%! message(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#message>
%
ctrlstrct:message(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#message',J).

%! next(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#next>
%
ctrlstrct:next(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#next',J).

%! next_sibling(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#next_sibling>
%
ctrlstrct:next_sibling(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#next_sibling',J).

%! parent_of(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#parent_of>
%
ctrlstrct:parent_of(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#parent_of',J).

%! should_be(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#should_be>
%
ctrlstrct:should_be(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#should_be',J).

%! subclass_of_arg(I,J)
%
%  As subclass_of_arg/2 , TODO
%
ctrlstrct:subclass_of_arg(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#arg'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_body(I,J)
%
%  As subclass_of_body/2 , TODO
%
ctrlstrct:subclass_of_body(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#body'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_body_item(I,J)
%
%  As subclass_of_body_item/2 , TODO
%
ctrlstrct:subclass_of_body_item(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#body_item'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_cause(I,J)
%
%  As subclass_of_cause/2 , TODO
%
ctrlstrct:subclass_of_cause(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#cause'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_contains_act(I,J)
%
%  As subclass_of_contains_act/2 , TODO
%
ctrlstrct:subclass_of_contains_act(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#contains_act'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_contains_child(I,J)
%
%  As subclass_of_contains_child/2 , TODO
%
ctrlstrct:subclass_of_contains_child(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#contains_child'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_corresponding_end(I,J)
%
%  As subclass_of_corresponding_end/2 , TODO
%
ctrlstrct:subclass_of_corresponding_end(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#corresponding_end'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_entry_point(I,J)
%
%  As subclass_of_entry_point/2 , TODO
%
ctrlstrct:subclass_of_entry_point(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#entry_point'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_executes(I,J)
%
%  As subclass_of_executes/2 , TODO
%
ctrlstrct:subclass_of_executes(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#executes'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_functions_item(I,J)
%
%  As subclass_of_functions_item/2 , TODO
%
ctrlstrct:subclass_of_functions_item(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#functions_item'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_global_code(I,J)
%
%  As subclass_of_global_code/2 , TODO
%
ctrlstrct:subclass_of_global_code(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#global_code'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_in_trace(I,J)
%
%  As subclass_of_in_trace/2 , TODO
%
ctrlstrct:subclass_of_in_trace(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#in_trace'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_next(I,J)
%
%  As subclass_of_next/2 , TODO
%
ctrlstrct:subclass_of_next(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#next'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_next_sibling(I,J)
%
%  As subclass_of_next_sibling/2 , TODO
%
ctrlstrct:subclass_of_next_sibling(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#next_sibling'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_parent_of(I,J)
%
%  As subclass_of_parent_of/2 , TODO
%
ctrlstrct:subclass_of_parent_of(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#parent_of'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_should_be(I,J)
%
%  As subclass_of_should_be/2 , TODO
%
ctrlstrct:subclass_of_should_be(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#should_be'),rdf(I,owl:someValuesFrom,J).

%! text_line(I,J)
%
%  Any relationship of type <http://vstu.ru/poas/ctrl_structs_2020-05_v1#text_line>
%
ctrlstrct:text_line(I,J):-rdf_has(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#text_line',J).

%! algorithm_name(I,J,K)
%
%  As algorithm_name/2  where asserted in graph
%
ctrlstrct:algorithm_name(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#algorithm_name',J,K).

%! arg(I,J,K)
%
%  As arg/2  where asserted in graph
%
ctrlstrct:arg(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#arg',J,K).

%! body(I,J,K)
%
%  As body/2  where asserted in graph
%
ctrlstrct:body(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#body',J,K).

%! body_item(I,J,K)
%
%  As body_item/2  where asserted in graph
%
ctrlstrct:body_item(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#body_item',J,K).

%! cause(I,J,K)
%
%  As cause/2  where asserted in graph
%
ctrlstrct:cause(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#cause',J,K).

%! contains_act(I,J,K)
%
%  As contains_act/2  where asserted in graph
%
ctrlstrct:contains_act(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#contains_act',J,K).

%! contains_child(I,J,K)
%
%  As contains_child/2  where asserted in graph
%
ctrlstrct:contains_child(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#contains_child',J,K).

%! corresponding_end(I,J,K)
%
%  As corresponding_end/2  where asserted in graph
%
ctrlstrct:corresponding_end(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#corresponding_end',J,K).

%! entry_point(I,J,K)
%
%  As entry_point/2  where asserted in graph
%
ctrlstrct:entry_point(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#entry_point',J,K).

%! exec_time(I,J,K)
%
%  As exec_time/2  where asserted in graph
%
ctrlstrct:exec_time(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#exec_time',J,K).

%! executes(I,J,K)
%
%  As executes/2  where asserted in graph
%
ctrlstrct:executes(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#executes',J,K).

%! expr_value(I,J,K)
%
%  As expr_value/2  where asserted in graph
%
ctrlstrct:expr_value(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#expr_value',J,K).

%! functions_item(I,J,K)
%
%  As functions_item/2  where asserted in graph
%
ctrlstrct:functions_item(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#functions_item',J,K).

%! global_code(I,J,K)
%
%  As global_code/2  where asserted in graph
%
ctrlstrct:global_code(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#global_code',J,K).

%! id(I,J,K)
%
%  As id/2  where asserted in graph
%
ctrlstrct:id(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#id',J,K).

%! in_trace(I,J,K)
%
%  As in_trace/2  where asserted in graph
%
ctrlstrct:in_trace(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#in_trace',J,K).

%! index(I,J,K)
%
%  As index/2  where asserted in graph
%
ctrlstrct:index(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#index',J,K).

%! message(I,J,K)
%
%  As message/2  where asserted in graph
%
ctrlstrct:message(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#message',J,K).

%! next(I,J,K)
%
%  As next/2  where asserted in graph
%
ctrlstrct:next(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#next',J,K).

%! next_sibling(I,J,K)
%
%  As next_sibling/2  where asserted in graph
%
ctrlstrct:next_sibling(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#next_sibling',J,K).

%! parent_of(I,J,K)
%
%  As parent_of/2  where asserted in graph
%
ctrlstrct:parent_of(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#parent_of',J,K).

%! should_be(I,J,K)
%
%  As should_be/2  where asserted in graph
%
ctrlstrct:should_be(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#should_be',J,K).

%! text_line(I,J,K)
%
%  As text_line/2  where asserted in graph
%
ctrlstrct:text_line(I,J,K):-rdf(I,'http://vstu.ru/poas/ctrl_structs_2020-05_v1#text_line',J,K).

